config/routes.rb
Rails.application.routes.draw do
  root 'homes#show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    password: 'users/password'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  resources :profiles, only: [:edit, :update, :show, :index] do
    member do
      get :followings, :followers
    end
  end
  resources :blogs do
    resources :comments
    resource :favorites, only:[:create, :destroy]
    collection do
      get :yourself_blog
    end
    member do
      get :other_blog
    end
  end
  resources :conversations do
    resources :messages
  end
  resources :favorites, only:[:index]
  resources :relationships, only: [:create, :destroy]
  #letter_opener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :drones, dependent: :destroy, inverse_of: :profile
  accepts_nested_attributes_for :drones, reject_if: :all_blank, allow_destroy: true
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  enum prefecture: {
    選択しない: '0',
    北海道: '1', 青森県: '2', 岩手県: '3', 宮城県: '4', 秋田県: '5', 山形県: '6', 福島県: '7',
    茨城県: '8', 栃木県: '9', 群馬県: '10', 埼玉県: '11', 千葉県: '12', 東京都: '13', 神奈川県: '14',
    新潟県: '15', 富山県: '16', 石川県: '17', 福井県: '18', 山梨県: '19', 長野県: '20',
    岐阜県: '21', 静岡県: '22', 愛知県: '23', 三重県: '24',
    滋賀県: '25', 京都府: '26', 大阪府: '27', 兵庫県: '28', 奈良県: '29', 和歌山県: '30',
    鳥取県: '31', 島根県: '32', 岡山県: '33', 広島県: '34', 山口県: '35',
    徳島県: '36', 香川県: '37', 愛媛県: '38', 高知県: '39',
    福岡県: '40', 佐賀県: '41', 長崎県: '42', 熊本県: '43', 大分県: '44', 宮崎県: '45', 鹿児島県: '46',
    沖縄県: '47'
  }

  def follow!(other_profile)
    active_relationships.create!(followed_id: other_profile.id)
  end

  def following?(other_profile)
    active_relationships.find_by(followed_id: other_profile.id)
  end

  def unfollow!(other_profile)
    active_relationships.find_by(followed_id: other_profile.id).destroy
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profile_q = Profile.includes(:user, :drones).ransack(params[:q])
    @profiles = @profile_q.result(distinct: true).order('created_at desc')
    @profile_q = Profile.ransack
  end

  def show
    @user = User.find(params[:id])
    @profile = @user.profile
    @drones = @profile.drones
  end

  def edit
    @user = User.find(params[:id])
    if current_user == @user
      @profile = @user.profile
      @profile.drones.build
    else
      redirect_to profile_path(current_user), notice:'他のユーザーは編集できません！'
    end
  end

  def update
    @user = User.find(params[:id])
    @profile = @user.profile
    if @profile.update(params_profile)
      redirect_to profile_path(current_user), notice: 'プロフィールを編集しました'
    else
      render :edit
    end
  end

  def followers
    @profile = Profile.find(params[:id])
    @profiles = @profile.followers
  end

  def followings
    @profile = Profile.find(params[:id])
    @profiles = @profile.followings
  end

  private

  def params_profile
    params.require(:profile).permit(
      :prefecture, :drone_name, :main_crop, :self_introduce,
      drones_attributes: [:id, :drone_name, :_destroy]
    )
  end
end

app/views/profiles/_drone_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col">
      <%= f.label :drone_name %>
    </div>
    <div class="col">
      <%= f.text_field :drone_name, placeholder: "MG-1 / 飛助 ect...", class:"form-control" %>
    </div>
    <div class="col"></div>
    <div class="col delete_drone">
      <%= link_to_remove_association "削除", f ,class:"btn btn-dark w-100" %>
    </div>
  </div>
</div>

app/views/profiles/_follow_form.html.erb
<div id="follow_form_<%= profile.id %>">
  <% unless current_user.profile.following?(profile) %>
    <%= form_with(model: current_user.profile.active_relationships.build(followed_id: profile.id), local: false) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: 'mt-3 btn btn-outline-secondary' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.profile.active_relationships.find_by(followed_id: profile.id), method: :delete, local: false) do |f| %>
      <%= f.submit "フォロー解除", class: 'mt-3 btn btn-secondary' %>
    <% end %>
  <% end %>
</div>

app/views/profiles/_search_user.html.erb
<%= search_form_for @profile_q do |f| %>
  <div class="container_search">
  <h5>【ユーザー検索】</h5>
    <div class="mb3">
      <%= f.label :prefecture, class:"form-label" %>
      <%= f.select :prefecture_eq, Profile.prefectures.keys.map, include_blank:'選択してください', class:"form-control" %>
    </div>
    <div class="mb3">
      <%= f.label :main_crop, class:"form-label" %>
      <%= f.search_field :main_crop_cont, placeholder: '生産作物で検索', class:"form-control"%>
    </div>
    <div class="mb3">
      <%= f.label :drone_name, class:"form-label"  %>
      <%= f.search_field :drones_drone_name_cont, placeholder: '機体名で検索', class:"form-control" %>
    </div>
    <div class="buttom_search">
      <div class="row">
        <div class="col"><%= f.submit " 検索 ", class:"btn btn-outline-dark w-100" %></div>
        <div class="col"><%= button_tag 'リセット', type: 'reset', class:"btn btn-outline-warning w-100" %></div>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>プロフィール設定</h1>

<%= form_with(model: @profile, local: true) do |f|   %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
    <p><%= @profile.errors.count %>件のエラーがあります。</p>
      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="edit_container">
    <div class="row">
      <div class="col">
        <%= f.label :prefecture %>
      </div>
      <div class="col">
        <%= f.select :prefecture, Profile.prefectures.keys, {}, class:"form-control" %>
      </div>
      <div class="col"></div>
      <div class="col"></div>
    </div>
    <br>
  <div class="conteiner_drone">
    <div class="mx-auto">
        <%= f.fields_for :drones do |d| %>
          <%= render 'drone_fields', f: d %>
        <% end %>
    <div id="detail-association-insertion-point"></div>
      <div class="col add_drone">
        <%= link_to_add_association "機体を追加", f, :drones,
          class:"btn btn-primary w-100",
          data: { 
            association_insertion_node: '#detail-association-insertion-point',
            association_insertion_method: 'before' } 
        %>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col">
      <%= f.label :main_crop %>
    </div>
    <div class="col">
      <%= f.text_field :main_crop, placeholder: "米/大豆/玉ねぎ etc...", class:"form-control" %>
    </div>
    <div class="col"></div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col">
    <%= f.label :self_introduce %>
    </div>
  </div class="text_form">
    <%= f.text_area :self_introduce, class:"form-control", id:"self_intro",
        placeholder: "◯◯県で農業をしている太郎といいます！主に米を生産していて防除にドローンを使用しています。防除だけでなく色々な使い方をしたい〜。" %>
  </div>
  <div class="profile_update">
    <%= f.submit "プロフィール設定を更新", class:"btn btn-outline-dark w-50" %>
  </div>
<% end %>

app/views/profiles/followers.html.erb
<h1>フォロワー</h1>
<% @profiles.includes([:user]).each do |profile| %>
  <div class="container_follower my-4">
    <div class="row">
      <div class="col">
        <% if profile.user.icon.present? %>
          <%= link_to image_tag(profile.user.icon.url, class: 'rounded-circle mr15', width: '60', height: '60'), profile_path(profile) %>
        <% else %>
          <%= link_to image_tag('guest_user.png', size: '60x60'), profile_path(profile) %>
        <% end %>
        <a id="name"> [ <%= profile.user.name %> ] </a>
      </div>
      <div class="col"><%= render 'follow_form', profile: profile %></div>
      <div class="col"></div>
    </div>
  </div>
<% end %>

app/views/profiles/followings.html.erb
<h1>フォロー</h1>
<% @profiles.includes([:user]).each do |profile| %>
  <div class="container_follower my-4">
    <div class="row">
      <div class="col">
        <% if profile.user.icon.present? %>
          <%= link_to image_tag(profile.user.icon.url, class: 'rounded-circle mr15', width: '60', height: '60'), profile_path(profile) %>
        <% else %>
          <%= link_to image_tag('guest_user.png', size: '60x60'), profile_path(profile) %>
        <% end %>
        <a id="name"><%= profile.user.name %></a>
      </div>
      <div class="col"><%= render 'follow_form', profile: profile %></div>
    </div>
  </div>
<% end %>

app/views/profiles/index.html.erb
<div class="index_user">
  <h1>登録ユーザーの一覧</h1>
</div>
<%= render 'search_user' %>
<% @profiles.each do |profile| %>
  <div class="container_profile">
    <div class="row">
      <div class="col">
        <% if profile.user.icon.present? %>
          <%= link_to image_tag(profile.user.icon.url, class: 'rounded-circle mr15', width: '60', height: '60'), profile_path(profile) %>
        <% else %>
          <%= link_to image_tag('guest_user.png', size: '60x60'), profile_path(profile) %>
        <% end %>
        <p id="name"> [ <%= profile.user.name %> ] </p>
      </div>
      <div class="col"><%= render 'follow_form', profile: profile %></div>
      <div class="col"><%= link_to 'DMを送る', conversations_path(sender_id: current_user.id, recipient_id: profile.user.id), method: :post, class:'mt-3 btn btn-outline-secondary' %></div>
    </div>
    <div class="row">
      <div class="col">
        <label>住居地</label>
      </div>
      <div class="col">
        <%= "-----" if profile.user.profile.prefecture.blank? %>
        <%= profile.user.profile.prefecture %>
      </div>
      <div class="col"></div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>所有ドローン</label>
      </div>
      <div class="col">
        <% profile.drones.each do |drone| %>
          <span>■<%= drone.drone_name %></span>
        <% end %>
      </div>
      <div class="col"></div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>主な生産作物</label>
      </div>
      <div class="col">
        <%= "-----" if profile.main_crop.blank? %>
        <%= profile.main_crop %>
      </div>
      <div class="col"></div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>自己紹介</label>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= "-----" if profile.self_introduce.blank? %>
        <%= profile.self_introduce %>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="profile_name">
  <% if current_user.id == @user.id %>
    <h1>マイページ</h1>
  <% else %>
    <h1><%= @user.name %>さんのページ</h1>
  <% end %>
</div>
<div class="container_icon">
  <% if @user.icon.present? %>
    <%= image_tag @user.icon.url, class: 'rounded-circle mr15', width: '150', height: '150' %>
  <% else %>
    <%= image_tag 'guest_user.png', size: '150x150' %>
  <% end %>
  <span><%= @user.name %></span>
  <a id="account_button">
    <% if current_user.id == @user.id %>
      <%= link_to ' アカウント設定', edit_user_registration_path(current_user), class:"btn btn-outline-secondary bi bi-pencil-square" %>
    <% end %>
  </a>
</div>
<div class="container_myprofile">
  <div class="row">
    <div class="col">
      <label>住居地</label>
    </div>
    <div class="col"> 
      <%= "-----" if @profile.prefecture.blank? %>
      <%= @profile.prefecture %>
    </div>
    <div class="col"></div>
  </div>
  <br>
  <div class="row">
    <div class="col">
      <label>所有ドローン</label>
    </div>
    <div class="col"> 
      <% @drones.each do |drone| %>
        <%= "-----" if drone.drone_name.blank? %>
        <span>■<%= drone.drone_name %></span>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
  <br>
  <div class="row">
    <div class="col">
      <label>主な生産作物</label>
    </div>
    <div class="col">
      <%= "-----" if @profile.main_crop.blank? %>
      <%= @profile.main_crop %>
    </div>
    <div class="col"></div>
  </div>
  <br>
  <div class="row">
    <div class="col">
      <label>自己紹介</label>
    </div>
    <div class="col"></div>
    <div class="col"></div>
  </div>
  <div class="row">
    <div class="col">
      <%= "-----" if @profile.self_introduce.blank? %>
      <%= @profile.self_introduce %>
    </div>
  </div>
</div>
<br>
<div class="bottun_list">
  <div class="row">
    <div class="col">
      <% if current_user.id == @user.id %>
        <%= link_to ' プロフィール設定', edit_profile_path(current_user), class:"btn btn-outline-secondary bi bi-pencil-square w-100" %>
      <% end %>
    </div>
    <div class="col">
      <p><%= link_to ' みんなの投稿', blogs_path, class: "btn btn-outline-primary bi bi-people-fill w-100" %></p>
      <br>
      <% if current_user.id == @user.id %>
        <p><%= link_to ' DM一覧', conversations_path, class: "btn btn-outline-dark bi bi-envelope-open w-100"%>
      <% end %>
    </div>
    <div class="col">
      <% if current_user.id == @user.id %>
        <p><%= link_to ' 自分の投稿一覧', yourself_blog_blogs_path, class: "btn btn-outline-primary bi bi-person-badge w-100" %></p>
        <br>
        <p><%= link_to ' お気に入り一覧', favorites_path, class:"btn btn-outline-dark bi bi-balloon-heart w-100" %></p>
      <% else %>
        <%= link_to "#{@profile.user.name}さんの投稿一覧", other_blog_blog_path(@profile.user), class:"btn btn-outline-primary w-100" %>
      <% end %>
    </div>
  </div>
</div>