config/routes.rb
Rails.application.routes.draw do
  root 'homes#show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    password: 'users/password'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  resources :profiles, only: [:edit, :update, :show, :index] do
    member do
      get :followings, :followers
    end
  end
  resources :blogs do
    resources :comments
    resource :favorites, only:[:create, :destroy]
    collection do
      get :yourself_blog
    end
    member do
      get :other_blog
    end
  end
  resources :conversations do
    resources :messages
  end
  resources :favorites, only:[:index]
  resources :relationships, only: [:create, :destroy]
  #letter_opener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :match_drones, dependent: :destroy
  has_many :drones, through: :match_drones
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :pesticide_type, presence: true
  validates :crop, presence: true
  validates :spray_area, presence: true
  validates :content, presence: true

  enum pesticide_type: {
    液剤: 1,
    液剤（肥料）: 2,
    粒剤: 3,
    粒剤（肥料）: 4,
    その他: 5
  }, _prefix: true #その他が重複しても使用できるような接頭辞

  enum crop: {
    稲: '稲', 麦類: '麦類', 大豆: '大豆', えだまめ: 'えだまめ', 玉ねぎ: '玉ねぎ',
    だいこん: 'だいこん', キャベツ: 'キャベツ', はくさい: 'はくさい', レタス: 'レタス', れんこん: 'れんこん',
    にんじん: 'にんじん', ブロッコリー: 'ブロッコリー', とうもろこし: 'とうもろこし', まつ: 'まつ', 果実類: '果樹類',
    その他野菜類: 'その他野菜類', その他: 'その他'
  }, _prefix: true

  enum status: { public: 0, private: 1 }, _prefix: true

  mount_uploader :picture, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @q = Blog.status_public.includes(:user, :match_drones, :drones).ransack(params[:q])
    @blogs = @q.result(distinct: true).order('created_at desc')
    @q = Blog.ransack
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.includes(:user, :drones).find(params[:id])
    @comments = @blog.comments
    @comment = @blog.comments.build
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)

    if @blog.status_private? && @blog.user != current_user
      redirect_to blogs_path, notice: 'このページにはアクセスできません！'
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: '新規作成しました！'
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
    if current_user.id != @blog.user_id
      redirect_to blogs_path, notice: '他のユーザーの日記は編集できません！'
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: '編集しました！'
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if current_user.id == @blog.user_id
      @blog.destroy
      redirect_to blogs_path, notice: 'ブログを削除しました！'
    else
      redirect_to blogs_path, notice: '他のユーザーの日記は削除できません！'
    end
  end

  def yourself_blog
    @search = Blog.where(user_id: current_user.id).includes(:user, :match_drones, :drones).ransack(params[:q])
    @blogs = @search.result(distinct: true).order('created_at desc')
    @search = Blog.where(user_id: current_user.id).ransack
  end

  def other_blog
    @blogs = Blog.status_public.where(user_id: params[:id]).includes(:user, :match_drones, :drones).order('created_at desc')
    @blog = @blogs.find_by(user_id: params[:id])
  end


  private

  def blog_params
    params.require(:blog).permit(
      :picture, :content, :work_date, :pesticide_type, :pesticide_name,
      :flight_speed, :rpm, :shutter_opening, :crop, :variety, :spray_area, :status, { drone_ids: [] }
    )
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def blog_content
    <<-"EOS".strip_heredoc
      散布で気づいたこと気になったことを入力しましょう！
      (例)初めて1キロ粒剤を散布した。説明書通りに散布したが剤が落ちすぎた。
      速度を少しあげて作業したらちょうど良く散布できた。
    EOS
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |f|   %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
    <p><%= @blog.errors.count %>件のエラーがあります。</p>
      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="edit_blog">
    <div class="field">
      <%= f.label :picture, class:"form-label" %>
      <%= f.file_field :picture, class:"form-control" %>
    </div>

    <div class="field">
      <%= f.label :work_date, class:"form-label" %>
      <%= f.date_select :work_date, class:"form-control" %>
    </div>

    <div class="field">
      <%= f.label :drone_name, class:"form-label" %>
      <a id="drones_name"><%= f.collection_check_boxes(:drone_ids, Drone.where(profile_id: current_user.id), :id, :drone_name) %></a>
    </div>

    <div class="field">
      <%= f.label :pesticide_type, class:"form-label" %>
      <%= f.select :pesticide_type, Blog.pesticide_types.keys, include_blank: '選択してください' %>
    </div>

    <div class="field">
      <%= f.label :pesticide_name, class:"form-label" %>
      <%= f.text_field :pesticide_name, placeholder: '◯◯１キロ粒剤', class:"form-control" %>
    </div>

    <div class="field">
      <%= f.label :flight_speed, class:"form-label" %><a>（数字のみご入力ください）</a>
      <%= f.text_field :flight_speed, placeholder: '時速18km', class:"form-control" %>
    </div>
    
    <div class="field">
      <%= f.label :rpm, class:"form-label" %><a>（数字のみご入力ください）</a>
      <%= f.text_field :rpm, placeholder: '1200回転(粒剤使用時のみ入力)', class:"form-control" %>
    </div>

    <div class="field">
      <%= f.label :shutter_opening, class:"form-label" %><a>（数字のみご入力ください）</a>
      <%= f.text_field :shutter_opening, placeholder: '18%(粒剤使用時のみ入力)', class:"form-control" %>
    </div>

    <div class="field">
      <%= f.label :crop, class:"form-label" %>
      <%= f.select :crop, Blog.crops.keys, include_blank: '選択してください' %>
    </div>

    <div class="field">
      <%= f.label :variety, class:"form-label" %>
      <%= f.text_field :variety, placeholder: 'コシヒカリ', class:"form-control" %>
    </div>

    <div class="field">
      <%= f.label :spray_area, class:"form-label" %><a>（数字のみご入力ください）</a>
      <%= f.text_field :spray_area, placeholder: '0.7ha' , class:"form-control"%>
    </div>

    <div class="field">
      <%= f.label :content, class:"form-label" %>
      <%= f.text_area :content, placeholder: blog_content, class:"form-control", id:"diary" %>
    </div>
    <br>
    <p>
      <%= f.label(:public, for: nil, class: 'blog_status_label') do %>
        <%= f.radio_button :status, :public %>
        <%= '公開(全てのユーザーに公開されます)' %>
      <% end %>
    </p>
    <p>
      <%= f.label(:private, for: nil, class: 'blog_status_label') do %>
        <%= f.radio_button :status, :private %>
        <%= '非公開(自分にのみ表示されます)' %>
      <% end %>
    </p>
    <%= f.submit "作成", class:"btn btn-outline-dark w-100" %>
  </div>
<% end %>

app/views/blogs/_index.html.erb
<% @blogs.each do |blog| %>
  <div class="all_blog_content">
    <div class="card" style="width: 25rem;">
      <div class="icon_user">
        <% if blog.user.icon.present? %>
          <%= link_to image_tag(blog.user.icon.url, class: 'rounded-circle mr15', width: '60', height: '60'), profile_path(blog.user_id) %>
        <% else %>
          <%= link_to image_tag('guest_user.png', class: 'rounded-circle mr15', width: '60', height: '60'), profile_path(blog.user_id) %>
        <% end %>
        <a><%= blog.user.name %></a>
        <% if blog.status_private? %>
          <a id="private_blog">【非公開中】</a>
        <% end %>
      </div>

      <% if blog.picture.present? %>
        <%= image_tag blog.picture.to_s, class:"card-img-top" %>
      <% else %>
        <%= image_tag 'No image.jpg', class:"card-img-top" %>
      <% end %>
    
      <div class="card-body">
        <div class="container">
          <div class="row justify-content-start">
            <div class="col-4"><label>作業実施日</label></div>
            <div class="col-4"><%= blog.work_date %></div>
          </div>
          <div class="row justify-content-start">
            <div class="col-4"><label>使用機体</label></div>
            <div class="col-4">
              <% blog.drones.each do |drone| %>
                <a>■</a><%= drone.drone_name %>
              <% end %> 
            </div>
          </div>
        <div class="row justify-content-start">
          <div class="col-4"><label>剤型</label></div>
          <div class="col-4"><%= blog.pesticide_type %></div>
        </div>
        <div class="row justify-content-start">
          <div class="col-4"><label>散布農薬名</label></div>
          <div class="col-4"><%= blog.pesticide_name %></div>
        </div>
        <div class="row justify-content-start">
          <div class="col-4"><label>散布作物</label></div>
          <div class="col-4"><%= blog.crop %></div>
        </div>
        <div class="row justify-content-start">
          <div class="col-4"><label>品種名</label></div>
          <div class="col-4">
            <% if blog.variety.present? %>
              <%= blog.variety %>
            <% else %>
              <%= ' ---- ' %>
            <% end %>
          </div>
        </div>
        <div class="row justify-content-start">
          <div class="col-4"><label>日記帳</label></div>
        </div>
        <div class="row justify-content-start">
          <div><%= truncate(blog.content, length: 50) %></div>
        </div>
        <br>
        <div class="row justify-content-start">
          <div class="col-4">
            <div id="favorite_blog_<%= blog.id %>">
              <%= render 'favorites/favorite',  blog: blog %>
            </div>
          </div>
          <div class="col"><%= link_to '', blog_path(blog), class:"btn btn-outline-dark bi bi-layout-text-sidebar-reverse",  data: {"turbolinks" => false} %></div>
          <div class="col">
            <% if current_user.id == blog.user_id %>
              <%= link_to '', edit_blog_path(blog), class:"btn btn-outline-dark bi bi-pencil-square" %>
            <% end %>
          </div>
          <div class="col">
            <% if current_user.id == blog.user_id %>
              <%= link_to '', blog_path(blog), method: :delete, data:{confirm:'本当に削除しても良いですか？'}, class:"btn btn-outline-danger bi bi-trash" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/_search_blog.html.erb
<div class="search_blog">
  <%= search_form_for @q do |f| %>
    <h5>【検索フォーム】</h5>
    <div class="mb3">
      <%= f.label :drone_name,'機体で検索', class:"form-label" %>
      <%= f.search_field :drones_drone_name_cont, placeholder: '機体名', class:"form-control" %>
    </div>
    <div class="mb3">
      <%= f.label :pesticide_type, class:"form-label" %>
      <br>
      <%= f.radio_button :pesticide_type_eq, '', {:checked => true}%>指定なし
      <%= f.radio_button :pesticide_type_eq, 1%>液剤 
      <%= f.radio_button :pesticide_type_eq, 2%>液剤（肥料）
      <%= f.radio_button :pesticide_type_eq, 3%>粒剤 
      <%= f.radio_button :pesticide_type_eq, 4%>粒剤（肥料）
      <%= f.radio_button :pesticide_type_eq, 5%>その他 
    </div>
    <div class="mb3">
      <%= f.label :pesticide_name, class:"form-label" %>
      <%= f.search_field :pesticide_name_cont, placeholder: '農薬名', class:"form-control" %>
    </div>
    <div class="mb3">
      <%= f.label :crop, '作物で検索', class:"form-label" %>
      <%= f.select :crop_eq, Blog.crops.keys.map, include_blank:'選択してください' %>
      <%= f.search_field :variety_cont, placeholder: '品種 (例：コシヒカリ)', class:"form-control" %>
    </div>
    <div class="mb3">
      <%= f.label :content, class:"form-label" %>
      <%= f.search_field :content_cont, placeholder: '日記帳のキーワード検索', class:"form-control" %>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <%= f.submit "検索", class:"btn btn-outline-dark w-100" %>
      </div>
      <div class="col">
        <%= button_tag 'リセット', type: 'reset', id: 'reset_button', class:"btn btn-outline-dark w-100" %>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/_search_yourblog.html.erb
<div class="search_blog">
  <%= search_form_for @search, url: yourself_blog_blogs_path do |f| %>
    <h5>【検索フォーム】</h5>
    <div class="mb3">
      <%= f.label :drone_name,'機体で検索', class:"form-label" %>
      <%= f.search_field :drones_drone_name_cont, placeholder: '機体名', class:"form-control" %>
    </div>
    <div class="mb3">
      <%= f.label :pesticide_type, class:"form-label" %>
      <br>
      <%= f.radio_button :pesticide_type_eq, '', {:checked => true}%>指定なし
      <%= f.radio_button :pesticide_type_eq, 1%>液剤 
      <%= f.radio_button :pesticide_type_eq, 2%>液剤（肥料）
      <%= f.radio_button :pesticide_type_eq, 3%>粒剤 
      <%= f.radio_button :pesticide_type_eq, 4%>粒剤（肥料）
      <%= f.radio_button :pesticide_type_eq, 5%>その他 
    </div>
    <div class="mb3">
      <%= f.label :pesticide_name, class:"form-label" %>
      <%= f.search_field :pesticide_name_cont, placeholder: '農薬名', class:"form-control" %>
    </div>
    <div class="mb3">
      <%= f.label :crop, '作物で検索', class:"form-label" %>
      <%= f.select :crop_eq, Blog.crops.keys.map, include_blank:'選択してください' %>
      <%= f.search_field :variety_cont, placeholder: '品種 (例：コシヒカリ)', class:"form-control" %>
    </div>
    <div class="mb3">
      <%= f.label :content, class:"form-label" %>
      <%= f.search_field :content_cont, placeholder: '日記帳のキーワード検索', class:"form-control" %>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <%= f.submit "検索", class:"btn btn-outline-dark w-100" %>
      </div>
      <div class="col">
        <%= button_tag 'リセット', type: 'reset', id: 'reset_button', class:"btn btn-outline-dark w-100" %>
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>みんなの投稿</h1>

<%= render 'search_blog' %>

<%= render 'index' %>

app/views/blogs/new.html.erb
<h1>新規作成</h1>

<%= render 'form' %>

app/views/blogs/other_blog.html.erb
<h1><%= @blog.user.name %>さんの投稿一覧</h1>

<%= render 'index' %>

app/views/blogs/show.html.erb
<h1>詳細</h1>

<div class="show_icon">
  <% if @blog.user.icon.present? %>
      <%= image_tag @blog.user.icon.url, class: 'rounded-circle mr15', width: '60', height: '60'  %>
  <% else %>
    <%= image_tag 'guest_user.png', size:'60x60' %>
  <% end %>
  <a><%= @blog.user.name %>
</div>

<div class="show_container">
  <div class="card" style="width: 30rem;">
    <% if @blog.picture.present? %>
      <%= image_tag @blog.picture.to_s, width:"60%", height:"40%", class:"card-img-top" %>
    <% else %>
      <%= image_tag 'No image.jpg', class:"card-img-top"%>
    <% end %>
  </div>

  <div class="container">
    <div class="row">
      <div class="col"><label>作業実施日</label></div>
      <div class="col"><%= @blog.work_date %></div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>使用した機体</label></div> 
      <div class="col">
        <% @blog.drones.each do |drone| %>
          <span>■</span><%= drone.drone_name %>
        <% end %>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>剤型</label></div>
      <div class="col"><%= @blog.pesticide_type %></div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>散布農薬名</label></div>
      <div class="col">
        <% if @blog.pesticide_name.present? %>
          <%= @blog.pesticide_name %>
        <% else %>
          <%= ' ---- ' %>
        <% end %>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>【機体設定情報】</label>
      <div class="col">
        <% if @blog.flight_speed.present? %>
          <%= " " %>
        <% else %>
          <%= '  ' %>
        <% end %>
        <a> </a>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label> ・飛行速度</label></div> 
      <div class="col">
        <% if @blog.flight_speed.present? %>
          <%= @blog.flight_speed %>
        <% else %>
          <%= ' ---- ' %>
        <% end %>
        <a> km/h</a>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label> ・インペラ回転数</label></div> 
      <div class="col">
        <% if @blog.rpm.present? %>
          <%= @blog.rpm %>
        <% else %>
          <%= ' ---- ' %>
        <% end %>
        <a> 回転</a>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label> ・シャッター開度</label></div>
      <div class="col">
        <% if @blog.shutter_opening.present? %>
          <%= @blog.shutter_opening %>
        <% else %>
          <%= '----' %>
        <% end %>
        <a>%</a>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>散布対象作物</label></div>
      <div class="col"><%= @blog.crop %></div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>品種名</label></div>
      <div class="col">
        <% if @blog.variety.present? %>
          <%= @blog.variety %>
        <% else %>
          <%= '----' %>
        <% end %>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>散布面積</label></div>
      <div class="col">
        <% if @blog.spray_area.present? %>
          <%= @blog.spray_area %>
        <% else %>
          <%= '----' %>
        <% end %>
        <a>ha</a>
      </div>
      <div class="col"></div>
    </div>
    <div class="row">
      <div class="col"><label>日記帳</label></div>
      <div class="col"></div>
      <div class="col"></div>
    </div>
    <div class="content">
      <%= @blog.content %>
    </div>
    <div class="row">
      <div class="col">
        <div id="favorite_<%=@blog.id %>">
          <%= render 'favorites/favorite', blog: @blog %>
        </div>
      </div>
    </div>

    <h5>コメント投稿</h5>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
    <div class="row">
      <div class="col"><%= link_to ' みんなの投稿', blogs_path, class:"btn btn-outline-primary w-100 bi bi-people-fill" %></div>
      <div class="col"><%= link_to ' お気に入り一覧', favorites_path, class:"btn btn-outline-dark w-100 bi bi-balloon-heart" %></div>
      <div class="col">
        <% if current_user.id == @blog.user_id %>
          <%= link_to '編集', edit_blog_path(@blog), class:"btn btn-outline-dark w-100 bi bi-pencil-square" %>
        <% end %>
      </div>
      <div class="col">
        <% if current_user.id == @blog.user_id %>
          <%= link_to '削除', blog_path(@blog), method: :delete, data:{confirm:'本当に削除しても良いですか？'}, class:"btn btn-outline-danger w-100 bi bi-trash" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/blogs/yourself_blog.html.erb
<h1>自分の投稿一覧</h1>

<%= render 'search_yourblog' %>

<%= render 'index' %>