config/routes.rb
Rails.application.routes.draw do
  root 'homes#show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    password: 'users/password'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  resources :profiles, only: [:edit, :update, :show, :index] do
    member do
      get :followings, :followers
    end
  end
  resources :blogs do
    resources :comments
    resource :favorites, only:[:create, :destroy]
    collection do
      get :yourself_blog
    end
    member do
      get :other_blog
    end
  end
  resources :conversations do
    resources :messages
  end
  resources :favorites, only:[:index]
  resources :relationships, only: [:create, :destroy]
  #letter_opener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorite_blogs.order(created_at: :desc)
  end

  def create
    @blog = Blog.find(params[:blog_id])
    @favorite = Favorite.new(user_id: current_user.id, blog_id: @blog.id)
    @favorite.save
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    @favorite = Favorite.find_by(user_id: current_user.id, blog_id: @blog.id)
    @favorite.destroy
  end
end

app/views/favorites/_favorite.html.erb
<% if current_user.favorited_by?(blog.id) %>
  <%= link_to blog_favorites_path(blog), class: "like-link", method: :delete, remote: true do %> 
    <i class="fa-solid fa-heart"></i>いいね済
  <% end %>
  <%= blog.favorites.count %></td>
<% else %>
  <%= link_to blog_favorites_path(blog), class: "like-link",method: :post, remote: true do %>
    <i class="fa-regular fa-heart"></i>いいね
  <% end %>
  <%= blog.favorites.count %></td>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_<%= @blog.id %>').html("<%= j(render "favorites/favorite", blog: @blog ) %>");
$('#favorite_blog_<%= @blog.id %>').html("<%= j(render "favorites/favorite", blog: @blog ) %>");

app/views/favorites/destroy.js.erb
$('#favorite_<%= @blog.id %>').html("<%= j(render "favorites/favorite", blog: @blog ) %>");
$('#favorite_blog_<%= @blog.id %>').html("<%= j(render "favorites/favorite", blog: @blog ) %>");

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<% if @favorites.present? %>
  <% @favorites.includes([:user, :drones]).each do |favorite| %>
  <div class="all_blog_content">
    <div class="card" style="width: 30rem;">
      <div class="icon_user">
        <% if favorite.user.icon.present? %>
          <%= image_tag favorite.user.icon.url, class: 'rounded-circle mr15', width: '60', height: '60' %>
        <% else %>
          <%= image_tag 'guest_user.png', class: 'rounded-circle mr15', width: '60', height: '60' %>
        <% end %>
        <a><%= favorite.user.name %></a>
      </div>
      <% if favorite.picture.present? %>
        <%= image_tag favorite.picture.to_s, class:"card-img-top"  %>
      <% else %>
        <%= image_tag 'No image.jpg', class:"card-img-top" %>
      <% end %>
      <div class="card-body">
        <div class="container">
          <div class="row justify-content-start">
            <div class="col-4"><label>作業実施日</label></div>
            <div class="col-4"><%= favorite.work_date %></div>
          </div>
          <div class="row justify-content-start">
            <div class="col-4"><label>使用機体</label></div>
            <div class="col-4">
              <% favorite.drones.each do |drone| %>
                <a>■</a><%= drone.drone_name %>
              <% end %> 
            </div>
          </div>
          <div class="row justify-content-start">
            <div class="col-4"><label>剤型</label></div>
            <div class="col-4"><%= favorite.pesticide_type %></div>
          </div>
          <div class="row justify-content-start">
            <div class="col-4"><label>散布農薬名</label></div>
            <div class="col-4"><%= favorite.pesticide_name %></div>
          </div>
          <div class="row justify-content-start">
            <div class="col-4"><label>散布作物</label></div>
            <div class="col-4"><%= favorite.crop %></div>
          </div>
          <div class="row justify-content-start">
            <div class="col-4"><label>品種名</label></div>
            <div class="col-4"><%= favorite.variety %></div>
          </div>
          <div class="row justify-content-start">
            <div class="col-4"><label>日記帳</label></div>
          </div>
          <div class="row justify-content-start">
            <div><%= truncate(favorite.content, length: 50) %></div>
          </div><br>
          <div class="row justify-content-start">
            <div class="col-4">
              <div id="favorite_blog_<%= favorite.id %>">
                <%= render 'favorites/favorite',  blog: favorite %>
              </div>
            </div>
            <div class="col"><%= link_to '詳細', blog_path(favorite), class:"btn btn-outline-dark" %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% end %>