config/routes.rb
Rails.application.routes.draw do
  root 'homes#show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    password: 'users/password'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  resources :profiles, only: [:edit, :update, :show, :index] do
    member do
      get :followings, :followers
    end
  end
  resources :blogs do
    resources :comments
    resource :favorites, only:[:create, :destroy]
    collection do
      get :yourself_blog
    end
    member do
      get :other_blog
    end
  end
  resources :conversations do
    resources :messages
  end
  resources :favorites, only:[:index]
  resources :relationships, only: [:create, :destroy]
  #letter_opener
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drysh</title>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <%# AOS %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%# Google Font %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https: //fonts.googleapis.com/css2? family= Kiwi+Maru:wght@300 & family= Klee+One & family=ムレチョ:wght@200 & display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/b38f983302.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg" style="background-color: #94b49f;">
        <div class="container-fluid">
          <%= link_to 'Drysh', root_path, class:"navbar-brand"  %>
          <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="ナビゲーションの切替">
            <span><i class="bi bi-list"></i></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <% if user_signed_in? %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link" %>
                <%= link_to ' みんなの投稿', blogs_path, class:"nav-link bi bi-people-fill" %>
                <%= link_to ' 新規投稿', new_blog_path, class:"nav-link bi bi-plus-square" %>
                <%= link_to ' 登録ユーザーの一覧', profiles_path, class:"nav-link bi bi-people" %>
                <%= link_to ' マイページ', profile_path(current_user.id), class:"nav-link bi bi-person-circle" %>
                <% if current_user.admin? %>
                  <%= link_to '管理者画面へ', rails_admin_path, class:"nav-link" %>
                <% end %>
              <% else %>
                <%= link_to " 新規登録", new_user_registration_path, class:"nav-link bi bi-person-plus-fill" %>
                <%= link_to "ログイン", new_user_session_path, class:"nav-link" %>
                <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:"nav-link" %>
                <%= link_to '管理者ログイン（閲覧用）', users_guest_admin_sign_in_path, method: :post, class:"nav-link"%>
              <% end %>
            </div><!-- /.navbar-nav -->
          </div><!-- /.navbar-collapse -->
        </div>
      </nav>
    </header>
    <main>
      <div class="notice_error">
        <% if notice %>
          <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-error"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
      <%# ページ内一番上に戻るボタン %>
      <%= link_to image_tag asset_path('arrow.png'), class: "arrow" %>
    </main>
    <footer>
      <p> ©Drysh 2022 / Created by Kanami Kumaki</p>
    </footer>
    <%# bootstrap %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%# AOS %>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>AOS.init();</script>
  </body>
</html>